version: '3.8'

services:
  client:
    build: ../packages/client
    image: frija/client:latest
    init: true

  ingress:
    build: ../packages/ingress
    depends_on:
      - client
      - server
    image: frija/ingress:latest
    init: true
    ports:
      - 80:80

  server:
    build: ../packages/server
    env_file: ./.env.dev
    image: frija/server:latest
    init: true
