name: Code Analysis

on:
  push:
  schedule:
    - cron: '0 5 * * 0' # At 05:00 on Sunday. https://crontab.guru/

jobs:
  perform-code-analysis:
    name: Perform code analysis
    runs-on: ubuntu-20.04 # Ubuntu LTS.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Initialize code analysis
        uses: github/codeql-action/init@v1
        with:
          languages: javascript

      - name: Perform code analysis
        uses: github/codeql-action/analyze@v1
