name: Continuous Integration

on: push

env:
  NODE_VERSION: 12.16.2 # Node LTS

jobs:
  build-packages:
    name: Build packages
    runs-on: ubuntu-18.04 # Ubuntu LTS
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.1.0

    - name: Setup Node
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install dependencies
      run: |
        npm ci
        npm run bootstrap

    - name: Build Ethereum package
      run: npx lerna run --scope @frija/ethereum build

    - name: Build server package
      run: npx lerna run --scope @frija/server build

  lint-files:
    name: Lint files
    runs-on: ubuntu-18.04 # Ubuntu LTS
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.1.0

    - name: Setup Node
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install dependencies
      run: |
        npm ci
        npm run bootstrap

    - name: Lint Markdown
      run: npm run lint:md

    - name: Lint Solidity
      run: npm run lint:sol

    - name: Lint Sass
      run: npm run lint:sass

    - name: Lint JavaScript
      run: npm run lint:js

  run-tests-and-report-code-coverage:
    name: Run tests and report code coverage
    runs-on: ubuntu-18.04 # Ubuntu LTS
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.1.0

    - name: Setup Node
      uses: actions/setup-node@v1.4.1
      with:
        node-version: ${{env.NODE_VERSION}}

    - name: Install dependencies
      run: |
        npm ci
        npm run bootstrap

    - name: Run tests
      run: npm run test:coverage

    - name: Report code coverage
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{secrets.CODECOV_TOKEN}}
